queue_scheme = "amqp"
queue_addr = "127.0.0.1"
queue_port = 5672
queue_username = "guest"
queue_password = "guest"

uri_queue_name = "dwh_uri_tasks"
uri_max_priority = 10
uri_prefetch_count = 1

img_queue_priority = 10

img_queue_name = "dwh_img_tasks"
img_max_priority = 10
img_prefetch_count = 1

store_addr = "http://localhost"
store_port = 11535
interpolation_method = 2

mongo_user_name = "dgaming"
mongo_user_pass = "dgaming"
mongo_host = "localhost:27017"
mongo_database = "dgaming"
mongo_collection = "token_metadata"

[[resolutions]]
width = 120
height = 90

[[resolutions]]
width = 200
height = 150
