version: '3'

services:
  indexer:
    image: "dwh_indexer:latest"
#    volumes:
#      - ./volumes/indexer.state:/root/indexer.state
    restart: unless-stopped
    networks:
      - dwh-tier

  img_storage:
    image: "dwh_img_storage:latest"
#    ports:
#      - "11535:11535"
#    volumes:
#      - ./volumes/img_storage:/root/dwh_storage
    expose:
      - 11535
    restart: unless-stopped
    networks:
      - dwh-tier

  token_meta_data:
    image: "dwh_tmd_worker:latest"
    restart: unless-stopped
    networks:
      - dwh-tier

  img_worker:
    image: "dwh_img_worker:latest"
    restart: unless-stopped
    networks:
      - dwh-tier

  mongo_daemon:
    image: "dwh_mongo_daemon:latest"
    restart: unless-stopped
    networks:
      - dwh-tier

  graphql:
    container_name: dwh_graphql
    image: hasura/graphql-engine:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - "indexer"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dgaming:dgaming@postgres:5432/marketplace
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    networks:
      - dwh-tier

networks:
  dwh-tier:
    external:
      name: dwh-network