version: '3'

services:
  indexer:
    image: "dwh_indexer:latest"
    restart: unless-stopped
    networks:
      - dwh-tier
#    network_mode: host

  img_storage:
    image: "dwh_img_storage:latest"
    ports:
      - "11535:11535"
    expose:
      - 11535
    restart: unless-stopped
    networks:
      - dwh-tier
  #    network_mode: host

  token_meta_data:
    image: "dwh_tmd_worker:latest"
    restart: unless-stopped
    networks:
      - dwh-tier
  #    network_mode: host

  img_worker:
    image: "dwh_img_worker:latest"
    restart: unless-stopped
    networks:
      - dwh-tier
  #    network_mode: host

  mongo_daemon:
    image: "dwh_mongo_daemon:latest"
    restart: unless-stopped
    networks:
      - dwh-tier
#    network_mode: host

networks:
  dwh-tier:
    driver: bridge
