version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: dwh_postgress
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dgaming
      - POSTGRES_PASSWORD=dgaming
      - POSTGRES_DB=marketplace
    networks:
      - dwh-tier

  mongodb:
    image: mongo:latest
    container_name: dwh_mongo
    restart: unless-stopped
#    ports:
#      - 27017:27017
    environment:
      - MONGODB_USER=dgaming
      - MONGODB_PASS=dgaming
      - MONGODB_DATABASE=dgaming
      - MONGO_INITDB_DATABASE=dgaming
      - MONGO_INITDB_ROOT_USERNAME=dgaming
      - MONGO_INITDB_ROOT_PASSWORD=dgaming
    networks:
      - dwh-tier

  rabbitmq:
    image: rabbitmq:latest
    container_name: dwh_rabbit
    restart: unless-stopped
#    ports:
#      - 5672:5672
#      - 15672:15672
    networks:
      - dwh-tier

#  graphql:
#    container_name: dwh_graphql
#    image: hasura/graphql-engine:latest
#    restart: unless-stopped
#    ports:
#      - 8080:8080
#    depends_on:
#      - "postgres"
#    environment:
#      - HASURA_GRAPHQL_DATABASE_URL=postgres://dgaming:dgaming@postgres:5432/marketplace
#      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
#    networks:
#      - dwh-tier

  marketplace:
    container_name: dwh_marketplace
    image: "dwh_marketplace:latest"
    restart: unless-stopped
    ports:
      - 26657:26657
      - 1317:1317
    networks:
      - dwh-tier
    environment:
      - MPD_INIT=true


#  marketplace_api:
#    container_name: dwh_marketplace_api
#    image: "dwh_marketplace:latest"
#    restart: unless-stopped
#    entrypoint: /bin/sh
#    command: -c "mpcli rest-server --chain-id mpchain --trust-node --laddr tcp:\\0.0.0.0:1317 --node=tcp://marketplace:26657"
#    ports:
#      - 1317:1317
#    networks:
#      - dwh-tier
##    network_mode: host

networks:
  dwh-tier:
    external:
      name: dwh-network